# Generated by Django 4.2.6 on 2023-10-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('type', models.CharField(choices=[('Pizza', 'Пицца'), ('Another', 'Другое')], default='Pizza', max_length=50, verbose_name='Тип')),
                ('character', models.TextField(max_length=100, verbose_name='Характеристика')),
                ('price', models.IntegerField(max_length=50, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'список товаров',
            },
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('number', models.CharField(max_length=150, verbose_name='Номер телефона')),
                ('message', models.CharField(max_length=200, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='completedrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_work', models.TextField(default='', verbose_name='Назначенное время и доп. условия')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.record', verbose_name='Выберите клиента')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи Выполненые',
                'db_table': 'completedrecord',
            },
        ),
    ]
